export const placeholderData = [
  {
    id: 1,
    name: "Penny Nickel",
    email: "penny@quarter.com",
    phone: "111-111-1111",
    bio: "oatmeal advocate",
    job: "Global Accounts Engineer",
  },
  {
    id: 2,
    name: "Elizabeth Santana",
    email: "santana@quarter.com",
    phone: "222-222-2222",
    bio: "ai advocate",
    job: "Global Accounts Engineer",
  },
  {
    id: 3,
    name: "chris Nickel",
    email: "chris@quarter.com",
    phone: "333-333-3333",
    bio: "chocolate advocate",
    job: "Global Accounts Engineer",
  },
  {
    id: 4,
    name: "Edward Jimbo",
    email: "penny@quarter.com",
    phone: "444-444-4444",
    bio: "cake advocate",
    job: "Global Accounts Engineer",
  },
  {
    id: 5,
    name: "Byron Nickel",
    email: "byron@quarter.com",
    phone: "555-555-5555",
    bio: "meat advocate",
    job: "Global Accounts Engineer",
  },
  {
    id: 6,
    name: "Gunna PushinP",
    email: "gunna@quarter.com",
    phone: "777-777-7220",
    bio: "computer advocate",
    job: "Global Accounts Engineer",
  },
];
